/**
 * @module github-commenter
 * @description Posts review comments to GitHub PRs via REST API (no octokit dependency).
 */

import type { ReviewSuggestion } from './response-parser.js';

interface PrContext {
  owner: string;
  repo: string;
  pullNumber: number;
  commitSha: string;
}

/**
 * Resolve PR context from GitHub Actions environment variables.
 */
export function resolvePrContext(): PrContext | null {
  const token = process.env['GITHUB_TOKEN'];
  const repository = process.env['GITHUB_REPOSITORY'];

  if (!token || !repository) return null;

  const [owner, repo] = repository.split('/');
  if (!owner || !repo) return null;

  // Try GITHUB_EVENT_PATH for PR number
  const prNumber = process.env['GITHUB_PR_NUMBER']
    ? parseInt(process.env['GITHUB_PR_NUMBER'], 10)
    : undefined;

  const commitSha = process.env['GITHUB_SHA'] ?? '';

  if (!prNumber) return null;

  return { owner, repo, pullNumber: prNumber, commitSha };
}

/**
 * Post a summary comment on a PR.
 */
export async function postSummaryComment(
  ctx: PrContext,
  suggestions: ReviewSuggestion[],
): Promise<boolean> {
  const token = process.env['GITHUB_TOKEN'];
  if (!token) return false;

  const body = formatSummary(suggestions);
  const url = `https://api.github.com/repos/${ctx.owner}/${ctx.repo}/issues/${ctx.pullNumber}/comments`;

  try {
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Accept': 'application/vnd.github+json',
        'Content-Type': 'application/json',
        'X-GitHub-Api-Version': '2022-11-28',
      },
      body: JSON.stringify({ body }),
    });
    return response.ok;
  } catch {
    return false;
  }
}

/**
 * Post inline review comments on specific lines.
 */
export async function postInlineComments(
  ctx: PrContext,
  suggestions: ReviewSuggestion[],
  fileLineMap: Map<string, { path: string; line: number }>,
): Promise<boolean> {
  const token = process.env['GITHUB_TOKEN'];
  if (!token) return false;

  const comments = suggestions
    .filter(s => fileLineMap.has(s.issueCode))
    .map(s => {
      const loc = fileLineMap.get(s.issueCode)!;
      return {
        path: loc.path,
        line: loc.line,
        body: `**${s.issueCode}** (${s.wcagCriterion ?? 'WCAG'})\n\n${s.explanation}\n\n\`\`\`diff\n${s.fix}\n\`\`\``,
      };
    });

  if (comments.length === 0) return true;

  const url = `https://api.github.com/repos/${ctx.owner}/${ctx.repo}/pulls/${ctx.pullNumber}/reviews`;

  try {
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Accept': 'application/vnd.github+json',
        'Content-Type': 'application/json',
        'X-GitHub-Api-Version': '2022-11-28',
      },
      body: JSON.stringify({
        commit_id: ctx.commitSha,
        body: 'ANDS A11y Review',
        event: 'COMMENT',
        comments,
      }),
    });
    return response.ok;
  } catch {
    return false;
  }
}

function formatSummary(suggestions: ReviewSuggestion[]): string {
  if (suggestions.length === 0) {
    return '## ANDS A11y Review\n\nNo accessibility issues found. :white_check_mark:';
  }

  const lines = [
    '## ANDS A11y Review',
    '',
    `Found ${suggestions.length} accessibility issue(s) with fix suggestions:`,
    '',
  ];

  for (const s of suggestions) {
    lines.push(`### ${s.issueCode}${s.wcagCriterion ? ` (${s.wcagCriterion})` : ''}`);
    lines.push('');
    lines.push(s.explanation);
    lines.push('');
    lines.push('```diff');
    lines.push(s.fix);
    lines.push('```');
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by ANDS a11y-bugbot*');

  return lines.join('\n');
}
