/**
 * @module editable-form/scaffold-template
 * @description Scaffold template for the editable-form pattern.
 *
 * Returns the files to generate when `ands scaffold --pattern editable-form` is run.
 * This is the core (adapter-agnostic) template. DS adapters may override this
 * by registering their own `scaffoldFiles` in their `PatternRegistration`.
 *
 * **Boundary rule:** This file must NOT import from Feature Lab or DS adapters.
 */

import type { ScaffoldFile, ScaffoldOptions } from '@ands/contracts';

export function editableFormScaffoldFiles(opts: ScaffoldOptions): ScaffoldFile[] {
  return [
    { filename: 'intent.js', content: intentFile(opts) },
    { filename: 'reducer.ts', content: reducerFile(opts) },
    { filename: 'styles.css', content: stylesFile(opts) },
    { filename: 'index.ts', content: indexFile(opts) },
  ];
}

function intentFile(opts: ScaffoldOptions): string {
  const formId = `${opts.name}-form`;
  return `/**
 * Intent for ${opts.name} editable form.
 *
 * Validate this file: ands validate ./intent.js
 * Read the schema:    packages/interaction-kit/src/editable-form/schema.ts
 */

/** @type {import('@ands/interaction-kit').EditableFormIntent} */
export const intent = {
  kind: 'editable-form',
  id: '${formId}',
  version: '1.0.0',
  description: '${opts.name} form — extend with your domain fields',
  fields: [
    {
      id: 'example-field',
      label: 'Example Field',
      type: 'text',
      required: true,
      placeholder: 'Enter a value',
    },
  ],
  logic: {
    onSuccess: 'toast',
    successMessage: 'Saved successfully.',
    onValidationError: 'scroll-to-field',
    onSubmitError: 'banner',
    requireConfirmation: false,
    resetOnSuccess: false,
    warnOnUnsavedChanges: true,
  },
  layout: {
    columns: 1,
    submitLabel: 'Save',
    cancelLabel: 'Cancel',
  },
};
`;
}

function reducerFile(opts: ScaffoldOptions): string {
  return `/**
 * Reducer for ${opts.name} form.
 * Generated by: ands scaffold --pattern editable-form
 *
 * Extend the state/events below for ${opts.name}-specific logic.
 * The exhaustive switch ensures TypeScript catches unhandled events.
 */
import {
  editableFormReducer,
  createInitialState,
  canSubmit,
  isLoading,
  getFieldErrors,
} from '@ands/interaction-kit';
import type {
  EditableFormState,
  EditableFormEvent,
} from '@ands/interaction-kit';

// Re-export the core reducer directly (extend if you need custom events)
export { editableFormReducer as reducer, createInitialState };
export type { EditableFormState as FormState, EditableFormEvent as FormEvent };

// --- Selector helpers for ${opts.name} ---
export { canSubmit, isLoading, getFieldErrors };
`;
}

function stylesFile(opts: ScaffoldOptions): string {
  return `/**
 * Styles for ${opts.name} form.
 * Generated by: ands scaffold --pattern editable-form
 *
 * Use token CSS variables instead of hardcoded values.
 * Run: ands audit-tokens  — to find any violations.
 */

/* Import the ANDS token layer */
/* @import '${opts.adapterPackage}/dist/tokens.css'; */

.${opts.name}-form {
  display: flex;
  flex-direction: column;
  gap: var(--spacing-4);           /* spacing.4 = 16px */
  padding: var(--spacing-6);       /* spacing.6 = 24px */
  background: var(--color-neutral-0);
  border-radius: var(--border-radius-lg);
  box-shadow: var(--shadow-base);
}

.${opts.name}-form__actions {
  display: flex;
  gap: var(--spacing-3);
  justify-content: flex-end;
  padding-top: var(--spacing-4);
  border-top: var(--border-width-thin) solid var(--color-neutral-200);
}

.${opts.name}-form__error-banner {
  padding: var(--spacing-3) var(--spacing-4);
  border-radius: var(--border-radius-base);
  background: color-mix(in srgb, var(--color-semantic-error) 10%, transparent);
  color: var(--color-semantic-error);
  font-size: var(--typography-size-sm);
}
`;
}

function indexFile(opts: ScaffoldOptions): string {
  return `/**
 * ${opts.name} form feature.
 * Generated by: ands scaffold --pattern editable-form
 */
export { intent } from './intent.js';
export { reducer, createInitialState, canSubmit, isLoading } from './reducer.js';
`;
}
