/**
 * @module build
 * @description Token build script — emits 3 artifacts to `dist/`:
 *
 * 1. `dist/tokens.css`        — CSS custom properties (e.g. `--color-brand-primary: #3B82F6`)
 * 2. `dist/tokens.ts`         — TypeScript string constants for IDE support
 * 3. `dist/tokens.index.json` — Flat JSON map (used by `ands audit-tokens`)
 *
 * Run via: `tsx src/build.ts` or `node dist/build.js` (after tsc).
 *
 * This script is part of the PRESET layer and emits from `referenceTokens`.
 * Adapters produce their own `tokens.index.json` via `ds-adapter-*` packages.
 */

import { writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath, pathToFileURL } from 'url';
import { referenceTokens } from './tokens.js';
import { flattenTokens } from './validator.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

// ---------------------------------------------------------------------------
// Path helpers
// ---------------------------------------------------------------------------

function distPath(filename: string): string {
  // When running from src/ (via tsx), output to ../../dist relative to src/
  // When running from dist/ (via node), output to ./
  const isSrc = __dirname.endsWith('/src') || __dirname.endsWith('\\src');
  const base = isSrc ? join(__dirname, '..', 'dist') : __dirname;
  return join(base, filename);
}

// ---------------------------------------------------------------------------
// CSS variable name from dot-path
// ---------------------------------------------------------------------------

function toCssVarName(path: string): string {
  return `--${path.replace(/\./g, '-')}`;
}

// ---------------------------------------------------------------------------
// TypeScript constant name from dot-path
// ---------------------------------------------------------------------------

function toTsConstName(path: string): string {
  return 'TOKEN_' + path.toUpperCase().replace(/[.\-]/g, '_');
}

// ---------------------------------------------------------------------------
// Build
// ---------------------------------------------------------------------------

export function runBuild(): void {
  const flat = flattenTokens(referenceTokens);

  // 1. tokens.index.json — flat path → value map (used by audit-tokens)
  const tokenIndex: Record<string, string | number> = {};
  for (const [path, { value }] of Object.entries(flat)) {
    tokenIndex[path] = value;
  }

  // 2. tokens.css — CSS custom properties
  const cssLines: string[] = [
    '/* Auto-generated by @ands/foundation-tokens — do not edit */',
    ':root {',
  ];
  for (const [path, { value }] of Object.entries(flat)) {
    cssLines.push(`  ${toCssVarName(path)}: ${String(value)};`);
  }
  cssLines.push('}', '');

  // 3. tokens.ts — TypeScript constants
  const tsLines: string[] = [
    '/* Auto-generated by @ands/foundation-tokens — do not edit */',
    '/* Import via: import { TOKEN_COLOR_BRAND_PRIMARY } from "@ands/foundation-tokens/dist/tokens.js" */',
    '',
  ];
  for (const [path, { value }] of Object.entries(flat)) {
    const constName = toTsConstName(path);
    const cssVar = toCssVarName(path);
    if (typeof value === 'string') {
      tsLines.push(`/** CSS: \`var(${cssVar})\` */`);
      tsLines.push(`export const ${constName} = '${value.replace(/'/g, "\\'")}' as const;`);
    } else {
      tsLines.push(`/** CSS: \`var(${cssVar})\` */`);
      tsLines.push(`export const ${constName} = ${value} as const;`);
    }
  }
  tsLines.push('');

  // Write artifacts
  const distDir = distPath('');
  mkdirSync(distDir, { recursive: true });

  writeFileSync(distPath('tokens.index.json'), JSON.stringify(tokenIndex, null, 2) + '\n');
  writeFileSync(distPath('tokens.css'), cssLines.join('\n'));
  writeFileSync(distPath('tokens.ts'), tsLines.join('\n'));

  console.log(`[ands/foundation-tokens] Build complete:`);
  console.log(`  tokens.index.json — ${Object.keys(tokenIndex).length} tokens`);
  console.log(`  tokens.css`);
  console.log(`  tokens.ts`);
}

// Run when executed directly
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  runBuild();
}
