/**
 * @module commands/scaffold
 * @description `ands scaffold --pattern <type> --output <dir>` — generates feature boilerplate.
 *
 * Generates:
 *   - `intent.js`     — intent object matching the pattern schema
 *   - `reducer.ts`    — state machine with exhaustive switch
 *   - `styles.css`    — CSS stub using token variables
 *   - `index.ts`      — barrel export
 *
 * Templates use token CSS variables and import from the adapter package
 * so the generated code is already compliant with ANDS conventions.
 *
 * **Output:** JSON to stdout. Files are written to `--output` directory.
 */

import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { join } from 'path';
import { ExitCode } from '../exit-codes.js';
import { makeOutput, emitOutput } from '../output.js';
import type { Issue } from '../output.js';

// ---------------------------------------------------------------------------
// Scaffold options
// ---------------------------------------------------------------------------

export interface ScaffoldOptions {
  /** Pattern type to scaffold. Currently: 'editable-form'. */
  pattern: string;
  /** Output directory path. */
  outputDir: string;
  /**
   * Feature name used in generated identifiers.
   * E.g. 'user-profile' → generates 'user-profile-form' intent ID.
   */
  featureName: string;
  /**
   * Adapter package to import from.
   * @default '@ands/ds-adapter-example'
   */
  adapterPackage?: string;
  /** Overwrite existing files. @default false */
  force?: boolean;
}

// ---------------------------------------------------------------------------
// Template generators
// ---------------------------------------------------------------------------

function generateIntentFile(opts: ScaffoldOptions): string {
  const formId = `${opts.featureName}-form`;
  return `/**
 * Intent for ${opts.featureName} editable form.
 *
 * Validate this file: ands validate ./intent.js
 * Read the schema:    packages/interaction-kit/src/editable-form/schema.ts
 */

/** @type {import('@ands/interaction-kit').EditableFormIntent} */
export const intent = {
  kind: 'editable-form',
  id: '${formId}',
  version: '1.0.0',
  description: '${opts.featureName} form — extend with your domain fields',
  fields: [
    {
      id: 'example-field',
      label: 'Example Field',
      type: 'text',
      required: true,
      placeholder: 'Enter a value',
    },
  ],
  logic: {
    onSuccess: 'toast',
    successMessage: 'Saved successfully.',
    onValidationError: 'scroll-to-field',
    onSubmitError: 'banner',
    requireConfirmation: false,
    resetOnSuccess: false,
    warnOnUnsavedChanges: true,
  },
  layout: {
    columns: 1,
    submitLabel: 'Save',
    cancelLabel: 'Cancel',
  },
};
`;
}

function generateReducerFile(opts: ScaffoldOptions): string {
  return `/**
 * Reducer for ${opts.featureName} form.
 * Generated by: ands scaffold --pattern editable-form
 *
 * Extend the state/events below for ${opts.featureName}-specific logic.
 * The exhaustive switch ensures TypeScript catches unhandled events.
 */
import {
  editableFormReducer,
  createInitialState,
  canSubmit,
  isLoading,
  getFieldErrors,
} from '@ands/interaction-kit';
import type {
  EditableFormState,
  EditableFormEvent,
} from '@ands/interaction-kit';

// Re-export the core reducer directly (extend if you need custom events)
export { editableFormReducer as reducer, createInitialState };
export type { EditableFormState as FormState, EditableFormEvent as FormEvent };

// --- Selector helpers for ${opts.featureName} ---
export { canSubmit, isLoading, getFieldErrors };

// --- Example: extending with feature-specific state ---
// If you need custom state, wrap the core reducer:
//
// export function ${opts.featureName.replace(/-/g, '')}Reducer(
//   state: EditableFormState,
//   event: EditableFormEvent,
// ): EditableFormState {
//   switch (event.type) {
//     case 'MY_CUSTOM_EVENT':
//       return { ...state, ... };
//     default:
//       return editableFormReducer(state, event);
//   }
// }
`;
}

function generateStylesFile(opts: ScaffoldOptions): string {
  return `/**
 * Styles for ${opts.featureName} form.
 * Generated by: ands scaffold --pattern editable-form
 *
 * Use token CSS variables instead of hardcoded values.
 * Run: ands audit-tokens  — to find any violations.
 */

/* Import the ANDS token layer */
/* @import '@ands/foundation-tokens/dist/tokens.css'; */

.${opts.featureName}-form {
  display: flex;
  flex-direction: column;
  gap: var(--spacing-4);           /* spacing.4 = 16px */
  padding: var(--spacing-6);       /* spacing.6 = 24px */
  background: var(--color-neutral-0);  /* color.neutral.0 = #FFFFFF */
  border-radius: var(--border-radius-lg); /* border.radius.lg = 8px */
  box-shadow: var(--shadow-base);  /* shadow.base */
}

.${opts.featureName}-form__actions {
  display: flex;
  gap: var(--spacing-3);           /* spacing.3 = 12px */
  justify-content: flex-end;
  padding-top: var(--spacing-4);
  border-top: var(--border-width-thin) solid var(--color-neutral-200);
}

.${opts.featureName}-form__error-banner {
  padding: var(--spacing-3) var(--spacing-4);
  border-radius: var(--border-radius-base);
  background: color-mix(in srgb, var(--color-semantic-error) 10%, transparent);
  color: var(--color-semantic-error);
  font-size: var(--typography-size-sm);
}
`;
}

function generateIndexFile(opts: ScaffoldOptions): string {
  return `/**
 * ${opts.featureName} form feature.
 * Generated by: ands scaffold --pattern editable-form
 */
export { intent } from './intent.js';
export { reducer, createInitialState, canSubmit, isLoading } from './reducer.js';
`;
}

// ---------------------------------------------------------------------------
// Command implementation
// ---------------------------------------------------------------------------

export async function runScaffold(options: ScaffoldOptions): Promise<number> {
  const { outputDir, pattern, featureName, force = false } = options;

  // Validate pattern
  const supportedPatterns = ['editable-form'];
  if (!supportedPatterns.includes(pattern)) {
    return emitOutput(
      makeOutput(
        'scaffold',
        false,
        ExitCode.ContractRuleFailure,
        `Unknown pattern: "${pattern}"`,
        [
          {
            category: 'scaffold',
            code: 'UNKNOWN_PATTERN',
            message: `Pattern "${pattern}" is not registered`,
            hint: `Supported patterns: ${supportedPatterns.join(', ')}`,
          },
        ],
      ),
    );
  }

  // Check output directory
  if (existsSync(outputDir) && !force) {
    return emitOutput(
      makeOutput(
        'scaffold',
        false,
        ExitCode.ContractRuleFailure,
        `Output directory already exists: ${outputDir}`,
        [
          {
            category: 'scaffold',
            code: 'OUTPUT_DIR_EXISTS',
            message: `Directory "${outputDir}" already exists`,
            hint: 'Use --force to overwrite existing files.',
          },
        ],
      ),
    );
  }

  // Generate files
  const filesToWrite: Array<{ filename: string; content: string }> = [];

  switch (pattern) {
    case 'editable-form': {
      filesToWrite.push(
        { filename: 'intent.js', content: generateIntentFile(options) },
        { filename: 'reducer.ts', content: generateReducerFile(options) },
        { filename: 'styles.css', content: generateStylesFile(options) },
        { filename: 'index.ts', content: generateIndexFile(options) },
      );
      break;
    }
    default: {
      // This is unreachable given the check above, but satisfies exhaustiveness
      const issues: Issue[] = [{
        category: 'internal',
        code: 'UNREACHABLE',
        message: 'Reached unreachable branch in scaffold switch',
      }];
      return emitOutput(makeOutput('scaffold', false, ExitCode.InternalError, 'Internal error', issues));
    }
  }

  // Write files
  try {
    mkdirSync(outputDir, { recursive: true });
    const written: string[] = [];
    for (const { filename, content } of filesToWrite) {
      const filePath = join(outputDir, filename);
      writeFileSync(filePath, content);
      written.push(filename);
    }

    return emitOutput(
      makeOutput(
        'scaffold',
        true,
        ExitCode.Success,
        `Scaffolded ${pattern} feature in ${outputDir}`,
        [],
        {
          data: {
            pattern,
            outputDir,
            filesWritten: written,
            nextStep: `ands validate ${join(outputDir, 'intent.js')}`,
          },
        },
      ),
    );
  } catch (e) {
    return emitOutput(
      makeOutput(
        'scaffold',
        false,
        ExitCode.InternalError,
        `Failed to write files: ${String(e instanceof Error ? e.message : e)}`,
        [
          {
            category: 'internal',
            code: 'FILE_WRITE_FAILURE',
            message: String(e instanceof Error ? e.message : e),
          },
        ],
      ),
    );
  }
}

// ---------------------------------------------------------------------------
// CLI argument parser
// ---------------------------------------------------------------------------

export interface ScaffoldArgs {
  pattern?: string;
  outputDir?: string;
  featureName?: string;
  adapterPackage?: string;
  force?: boolean;
}

export function parseScaffoldArgs(args: string[]): ScaffoldArgs {
  const result: ScaffoldArgs = {};
  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--pattern' && args[i + 1]) {
      result.pattern = args[i + 1];
      i++;
    } else if (args[i] === '--output' && args[i + 1]) {
      result.outputDir = args[i + 1];
      i++;
    } else if (args[i] === '--name' && args[i + 1]) {
      result.featureName = args[i + 1];
      i++;
    } else if (args[i] === '--adapter' && args[i + 1]) {
      result.adapterPackage = args[i + 1];
      i++;
    } else if (args[i] === '--force') {
      result.force = true;
    }
  }
  return result;
}

// ---------------------------------------------------------------------------
// Help text
// ---------------------------------------------------------------------------

export const SCAFFOLD_HELP = `
ands scaffold --pattern <type> --output <dir> [options]

  Generate boilerplate for a new feature using an Interaction Kit pattern.

  Required:
    --pattern <type>    Pattern type (currently: editable-form)
    --output <dir>      Output directory path

  Options:
    --name <name>       Feature name for generated identifiers (default: my-feature)
    --adapter <pkg>     Adapter package to import from (default: @ands/ds-adapter-example)
    --force             Overwrite existing files

  Output:    JSON to stdout + files written to --output dir

  Exit codes:
    0  Files generated
    4  Unknown pattern or directory exists (use --force)
    5  File write failure

  Generated files:
    intent.js     — intent object (run ands validate on this)
    reducer.ts    — state machine with exhaustive switch
    styles.css    — CSS stub using token variables
    index.ts      — barrel export

  Example:
    ands scaffold --pattern editable-form --output src/features/user-profile --name user-profile
    ands validate src/features/user-profile/intent.js
`.trim();
